services:
  db:
    container_name: mysql_db
    image: mysql:9.1.0
    volumes:
      - ./event-vol:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYAPP_DB_ROOT_PASSWORD}
      MYSQL_USER: ${MYAPP_DB_USER}
      MYSQL_PASSWORD: ${MYAPP_DB_PASSWORD}
      MYSQL_DATABASE: ${MYAPP_DB_DATABASE}
    restart: always
  
  phpMyAdmin:
    depends_on:
      - db
    container_name: phpMyAdmin
    image: phpmyadmin:5.2.0-apache
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  event-vol:
    external: false
